"""fixed bugs

Revision ID: 1e7095809ebc
Revises: e7f4efefd434
Create Date: 2026-04-12 15:35:27.661515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7095809ebc'
down_revision: Union[str, Sequence[str], None] = 'e7f4efefd434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.NUMERIC(precision=1, scale=1),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=1, scale=1),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
